import React from 'react'
import { FileText, ArrowLeft, AlertCircle, Mail } from 'lucide-react'
import Logo from '../Logo'

interface TermsPageProps {
  onBack: () => void
  onOpenPrivacy?: () => void
  onOpenContact?: () => void
}

export const TermsOfService: React.FC<TermsPageProps> = ({ onBack, onOpenPrivacy, onOpenContact }) => {
  return (
    <div className="min-h-screen bg-[#FDFDFD] text-[#192837] font-body">
      {/* Header Bar */}
      <header className="sticky top-0 z-30 bg-white/90 backdrop-blur-md border-b border-[#192837]/10 px-5 sm:px-8 py-4">
        <div className="max-w-[1100px] mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button
              onClick={onBack}
              className="p-2 rounded-xl bg-[#F2F2EE] hover:bg-[#e6e6e0] transition-all text-[#192837] cursor-pointer flex items-center gap-1.5 text-xs font-bold"
            >
              <ArrowLeft size={16} />
              <span>Back to Home</span>
            </button>
            <div className="flex items-center gap-2 border-l border-[#192837]/15 pl-3">
              <Logo size={28} />
              <span className="font-heading font-extrabold text-base tracking-tight text-[#192837]">
                Cyber<span className="text-[#7342E2]">Trace</span>
              </span>
            </div>
          </div>

          <div className="flex items-center gap-3 text-xs font-semibold">
            {onOpenPrivacy && (
              <button onClick={onOpenPrivacy} className="hover:text-[#7342E2] transition-colors cursor-pointer">
                Privacy Policy
              </button>
            )}
            {onOpenContact && (
              <button onClick={onOpenContact} className="hover:text-[#7342E2] transition-colors cursor-pointer">
                Contact
              </button>
            )}
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="max-w-[900px] mx-auto px-5 sm:px-8 py-12 sm:py-16 text-left">
        <div className="mb-10">
          <div className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-[#7342E2]/10 text-[#7342E2] text-xs font-extrabold tracking-wide uppercase mb-3">
            <FileText size={14} />
            <span>Platform Agreement & Usage Terms</span>
          </div>
          <h1 className="font-heading text-3xl sm:text-4xl font-extrabold text-[#192837] tracking-tight mb-2">
            Terms of Service
          </h1>
          <p className="text-xs text-[#192837]/60 font-medium">
            Effective Date: September 2026 • Platform: CyberTrace / Email Threat Intelligence
          </p>
        </div>

        <div className="space-y-10 text-xs sm:text-sm text-[#192837]/85 leading-relaxed font-normal">
          {/* Section 1 */}
          <section className="space-y-3">
            <h3 className="font-heading text-lg font-bold text-[#192837]">1. Acceptance of Terms</h3>
            <p>
              By accessing, browsing, or using CyberTrace (<strong>"the Platform"</strong>, <strong>"we"</strong>, <strong>"our"</strong>), or by connecting your Google/Gmail account, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Platform.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3">
            <h3 className="font-heading text-lg font-bold text-[#192837]">2. Service Description & Permitted Purpose</h3>
            <p>
              CyberTrace is an enterprise defensive security tool engineered to provide:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Automated email threat inspection (Phishing, BEC, Impersonation, Malicious URLs).</li>
              <li>Sender IP intelligence, proxy/VPN reputation checks, and approximate relay geolocation.</li>
              <li>Gemini AI forensic threat explanation and RFC email authentication analysis.</li>
              <li>SOC investigator triage and automated early warning notification delivery.</li>
            </ul>
          </section>

          {/* Section 3: AI Disclaimer */}
          <section className="space-y-3">
            <h3 className="font-heading text-lg font-bold text-[#192837]">3. AI-Generated Intelligence & Security Disclaimer</h3>
            <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-900">
              <div className="flex items-start gap-2.5">
                <AlertCircle size={18} className="text-amber-700 mt-0.5 shrink-0" />
                <div className="space-y-1">
                  <p className="font-bold text-xs">Advisory Nature of Threat Scoring</p>
                  <p className="text-xs leading-relaxed">
                    Threat scores, risk assessments, and forensic intelligence generated by CyberTrace are powered by machine learning algorithms, heuristic heuristics, and Gemini AI. While designed for high precision, they are advisory tools intended to assist security teams and users. CyberTrace does not guarantee 100% detection of zero-day threats or the complete absence of false positives.
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* Section 4: Acceptable Use */}
          <section className="space-y-3">
            <h3 className="font-heading text-lg font-bold text-[#192837]">4. Acceptable Use Policy</h3>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Platform to scan, intercept, or analyze email accounts for which you do not possess explicit authorization.</li>
              <li>Reverse engineer, exploit, or attempt unauthorized penetration testing against platform APIs or infrastructure.</li>
              <li>Use the Platform to build competing threat vectors or evade security defenses.</li>
            </ul>
          </section>

          {/* Section 5: Disconnection & Termination */}
          <section className="space-y-3">
            <h3 className="font-heading text-lg font-bold text-[#192837]">5. Account Termination & Data Purge</h3>
            <p>
              You may disconnect your Google Workspace/Gmail account or request permanent deletion of all stored security scan data at any time via the user profile dashboard. We reserve the right to suspend or terminate accounts that violate these terms.
            </p>
          </section>

          {/* Section 6: Limitation of Liability */}
          <section className="space-y-3">
            <h3 className="font-heading text-lg font-bold text-[#192837]">6. Limitation of Liability</h3>
            <p>
              To the maximum extent permitted by applicable law, CyberTrace and its maintainers shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use or inability to use the service, including security incidents occurring outside the scope of platform monitoring.
            </p>
          </section>

          {/* Section 7: Contact */}
          <section className="space-y-3 pt-4 border-t border-[#192837]/10">
            <h3 className="font-heading text-lg font-bold text-[#192837]">7. Inquiries</h3>
            <p>Questions regarding these Terms of Service may be addressed to:</p>
            <div className="p-4 rounded-xl bg-[#F8F8F6] border border-[#192837]/10 flex items-center gap-3">
              <Mail size={18} className="text-[#7342E2]" />
              <div>
                <p className="text-xs font-bold text-[#192837]">CyberTrace Compliance & Security</p>
                <p className="text-xs text-[#7342E2] font-semibold">admin@cybertrace.local</p>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  )
}

export default TermsOfService
